# MapSlopper fuzz harness.
#
# Generates N random closed simple polygons + random heightmaps, runs the
# CLI, then runs q3map2 -meta on each result. Reports any iteration where:
#   * the CLI returned non-zero
#   * q3map2 returned non-zero
#   * q3map2 reported "0 total world brushes" (silent rejection)
#   * the resulting .bsp file is suspiciously small (< 1 KB)
#
# Usage:
#   pwsh ./scripts/fuzz.ps1 -Count 100 -Q3Map2 "$env:TEMP\netradiant-custom\q3map2.exe"
#
# Polygons are generated by sampling random angles around a centre, sorting
# them, and placing each vertex at a random radius. This guarantees a simple
# (non-self-intersecting) star-shaped polygon and exercises 3..N vertices.

[CmdletBinding()]
param(
    [int]$Count = 50,
    [int]$Seed = 0,
    [string]$Q3Map2 = "$env:TEMP\netradiant-custom\q3map2.exe",
    [string]$Cli = "src/MapSlopper.Cli/bin/Debug/net5.0/MapSlopper.Cli.exe",
    [int]$MinVerts = 3,
    [int]$MaxVerts = 16,
    [switch]$KeepFailures
)

$ErrorActionPreference = 'Stop'
if (-not (Test-Path $Q3Map2)) { throw "q3map2 not found at $Q3Map2" }
if (-not (Test-Path $Cli))    { throw "CLI not found at $Cli (run dotnet build src/MapSlopper.Cli first)" }

$rng = if ($Seed -gt 0) { [System.Random]::new($Seed) } else { [System.Random]::new() }

function New-Polygon {
    param([int]$N, [double]$Cx, [double]$Cy, [double]$Rmin, [double]$Rmax)
    # Sample N random angles, sort them => simple polygon viewed from centre.
    $angles = 1..$N | ForEach-Object { $rng.NextDouble() * [Math]::PI * 2 } | Sort-Object
    $pts = foreach ($a in $angles) {
        $r = $Rmin + $rng.NextDouble() * ($Rmax - $Rmin)
        [pscustomobject]@{
            x = [Math]::Round($Cx + [Math]::Cos($a) * $r, 0)
            y = [Math]::Round($Cy + [Math]::Sin($a) * $r, 0)
        }
    }
    return ,$pts
}

function New-Project {
    param([int]$Iter)
    $n      = $rng.Next($MinVerts, $MaxVerts + 1)
    $cx     = 1024 + $rng.Next(0, 8192)
    $cy     = 1024 + $rng.Next(0, 8192)
    $rmin   = 64 + $rng.Next(0, 256)
    $rmax   = $rmin + 64 + $rng.Next(0, 768)
    $pts    = New-Polygon -N $n -Cx $cx -Cy $cy -Rmin $rmin -Rmax $rmax

    # Build outline JSON (graph form: points + edges in cycle order).
    $points = @()
    $ids = @()
    foreach ($p in $pts) {
        $id = [guid]::NewGuid().ToString()
        $ids += $id
        $points += [pscustomobject]@{ id = $id; x = $p.x; y = $p.y }
    }
    $edges = @()
    for ($i = 0; $i -lt $ids.Count; $i++) {
        $edges += [pscustomobject]@{ a = $ids[$i]; b = $ids[($i + 1) % $ids.Count] }
    }

    # Heightmap covering the centre with random raw values (kept small so they
    # don't punch the auto-ceiling). 1 raw unit = 1 Quake unit.
    $cellSize = 32
    $hmW = 96
    $hmH = 96
    $originX = $cx - ($hmW * $cellSize / 2)
    $originY = $cy - ($hmH * $cellSize / 2)
    $bytes = New-Object byte[] ($hmW * $hmH * 2)
    for ($i = 0; $i -lt $hmW * $hmH; $i++) {
        $v = $rng.Next(0, 192) # 0..191 Quake units
        $bytes[$i * 2]     = [byte]($v -band 0xFF)
        $bytes[$i * 2 + 1] = [byte](($v -shr 8) -band 0xFF)
    }
    $b64 = [Convert]::ToBase64String($bytes)

    $proj = [pscustomobject]@{
        formatVersion        = 1
        outline              = [pscustomobject]@{ points = $points; edges = $edges }
        heightmap            = [pscustomobject]@{
            width = $hmW; height = $hmH; cellSize = $cellSize
            originX = $originX; originY = $originY
            dataBase64 = $b64
        }
        ceilingHeight        = 256 + $rng.Next(0, 256)
        wallThickness        = 16
        floorTexture         = "base_floor/clang_floor"
        wallTexture          = "base_wall/atech1_4"
        ceilingTexture       = "base_ceiling/ceil1_3"
        playerStartOverride  = $null
        lightSpacing         = 256 + $rng.Next(0, 512)
        lightIntensity       = 300
        lightInsetFromCeiling = 16
        ceilingThickness     = 16
        floorBaseThickness   = 16
    }
    return $proj
}

$work = Join-Path $env:TEMP "mapslopper-fuzz"
Remove-Item -Recurse -Force $work -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $work,"$work\baseq3","$work\maps","$work\projects" | Out-Null

$failures = New-Object System.Collections.Generic.List[object]
$passCount = 0
$leakCount = 0
$startTime = Get-Date

for ($iter = 1; $iter -le $Count; $iter++) {
    $proj = New-Project -Iter $iter
    $projPath = Join-Path "$work\projects" "p$iter.json"
    $mapPath  = Join-Path "$work\maps"     "p$iter.map"
    $bspPath  = [System.IO.Path]::ChangeExtension($mapPath, ".bsp")
    $proj | ConvertTo-Json -Depth 10 | Set-Content -Path $projPath -Encoding UTF8

    # 1. CLI build
    $cliOut = & $Cli build $projPath -o $mapPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        $failures.Add([pscustomobject]@{
            iter = $iter; stage = "cli"; exit = $LASTEXITCODE
            project = $projPath; output = ($cliOut -join "`n")
        })
        Write-Host "[$iter] CLI FAIL ($LASTEXITCODE)" -ForegroundColor Red
        continue
    }

    # 2. q3map2 -meta
    Remove-Item $bspPath -Force -ErrorAction SilentlyContinue
    $q3Out = & $Q3Map2 -fs_basepath $work -fs_game baseq3 -meta $mapPath 2>&1
    $q3Combined = $q3Out -join "`n"
    $q3Exit = $LASTEXITCODE

    $worldBrushes = ([regex]::Match($q3Combined, '(\d+)\s+total meta surfaces')).Groups[1].Value
    if ([string]::IsNullOrEmpty($worldBrushes)) {
        $worldBrushes = ([regex]::Match($q3Combined, '(\d+)\s+total world brushes')).Groups[1].Value
    }
    $bspSize = if (Test-Path $bspPath) { (Get-Item $bspPath).Length } else { 0 }

    $bad = $false
    $reasons = @()
    if ($q3Exit -ne 0)               { $bad = $true; $reasons += "exit=$q3Exit" }
    if ($worldBrushes -eq "0")       { $bad = $true; $reasons += "0 world brushes" }
    if ($bspSize -lt 1024)           { $bad = $true; $reasons += "bsp=$bspSize" }
    # Note: q3map2 may report "leaked" for concave / star-shaped polygons
    # whose wall ring does not seal at reflex corners. That is a level-design
    # consequence of the chosen outline, not a generator-correctness bug, so
    # we surface it as a warning rather than a failure.
    $leaked = $q3Combined -match '\*+\s*leaked\s*\*+'

    if ($bad) {
        $failures.Add([pscustomobject]@{
            iter = $iter; stage = "q3map2"; exit = $q3Exit
            worldBrushes = $worldBrushes; bspSize = $bspSize
            reasons = ($reasons -join ", ")
            project = $projPath; output = $q3Combined
        })
        Write-Host "[$iter] FAIL ($($reasons -join ', '))" -ForegroundColor Red
    } else {
        $passCount++
        if ($leaked) { $leakCount++ }
        if ($iter % 10 -eq 0 -or $iter -le 5) {
            $tag = if ($leaked) { "OK (leak)" } else { "OK" }
            Write-Host "[$iter] $tag (brushes=$worldBrushes, bsp=$bspSize)" -ForegroundColor Green
        }
    }

    # Cleanup successful artifacts to keep disk usage bounded.
    if (-not $bad -or -not $KeepFailures) {
        Remove-Item $mapPath, $bspPath, "$work\maps\p$iter.srf" -Force -ErrorAction SilentlyContinue
        if (-not $bad) { Remove-Item $projPath -Force -ErrorAction SilentlyContinue }
    }
}

$elapsed = (Get-Date) - $startTime
Write-Host "`n=== FUZZ SUMMARY ===" -ForegroundColor Cyan
Write-Host ("Passed: {0} / {1}    Failed: {2}    Elapsed: {3:F1}s" -f `
    $passCount, $Count, $failures.Count, $elapsed.TotalSeconds)
Write-Host ("  (of which {0} compiled with q3map2 leak warnings -- non-fatal)" -f $leakCount)

if ($failures.Count -gt 0) {
    Write-Host "`n--- First 5 failures ---" -ForegroundColor Yellow
    $failures | Select-Object -First 5 | ForEach-Object {
        Write-Host ("[{0}] {1}: {2}" -f $_.iter, $_.stage, ($_.reasons ?? $_.exit)) -ForegroundColor Yellow
        Write-Host "  project: $($_.project)"
        $tail = ($_.output -split "`n" | Select-Object -Last 5) -join "`n  "
        Write-Host "  output:`n  $tail"
    }
    exit 1
}
exit 0
